@host=https://localhost:7155

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Mits",
    "lastName": "Ramos",
    "email": "mitchell@example.com",
    "password": "securePassword"
}